
 <?php 
    session_start();
    ?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Blog Femme Moderne</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="vendor/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous"> 
    <link rel="stylesheet" href="vendor/font-awesome/css/font-awesome.min.css">
    
    <!-- Custom icon font-->
    <link rel="stylesheet" href="css/fontastic.css">
    <!-- Google fonts - Open Sans-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Fancybox-->
    <link rel="stylesheet" href="vendor/@fancyapps/fancybox/jquery.fancybox.min.css">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="css/style.sea.css" id="theme-stylesheet" >
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="css/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="favicon.png">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
    <header class="header"id="header">
      <!-- Main Navbar-->
      <nav class="navbar navbar-expand-lg"> 
        <div class="container">
          <!-- Navbar Brand -->
          <div class="navbar-header d-flex align-items-center justify-content-between ">
            <a href="blog.php" class="navbar-brand"><img src="img/log.jpg" width="100px"></a>
            <!-- Navbar Brand -->
            <!-- Toggle Button-->
            <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
          </div>
          <!-- Navbar Menu -->
          <div id="navbarcollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto"> 
              <li class="nav-item"><a href="blog.php" class="nav-link active ">Accueil</a>
              </li>
             <?php  foreach($categories as $indexCategories => $category): 
                      if($category['nbart']>0): ?>
              <li class="nav-item " ><a class="nav-link" href="postsByCategory.php?idCategory=<?= $category['id'] ?>" data-id="<?= $v['id'] ?>" ><?=$category['name']?></a>
              </li>
              <?php endif; endforeach; 
              if(isset($_SESSION['pseudo']) && $_SESSION['privilégie'] == "admin" ):?>
                <li class="nav-item"><a href="admin/showPosts.php" class="btn btn-info ">Adminstration</a>
              </li>
               <?php endif;?>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
      <div class="row">
          
            <!-- Chargement du template PHTML spécifié par le programme PHP -->
            <?php include $template.'.phtml' ?>
       
  
    <aside class="col-lg-4 ">
    <!-- Widget Connexion-->
      <div class="widget search">
        <?php
        if(isset($_SESSION['pseudo']) && $_SESSION['pseudo'] != "" ): ?>
        <div class="d-flex justify-content-between">
          <span class="h6">Bienvenue <em><?=$_SESSION['last_Name']  ?> <?=$_SESSION['first_Name']  ?></em></span>
          <a href="logOut.php" class=" btn btn-danger" title="signOut" ><i class="fas fa-sign-out-alt"></i></a>
        </div>
      <?php endif;if(!isset($_SESSION['pseudo'])||$_SESSION['pseudo'] == "" ): ?>
      <p class="h6">Connexion:</p>
        <form method="POST" action="login.php" class="form-group">
          <input id="mail" type="mail" name="mail" placeholder="Email ">
          <div class="d-flex justify-content-between mt-2">
              <input id="password" type="password" name="password" placeholder="Password">
               <button type="submit" name="btnSubmit" id="submit" class="btn btn-primary "><i class="fas fa-sign-in-alt"></i>
               </button>
          </div>
        </form>
        <p >Nouveau dans notre blog !<a href="signUp.php"  class="nav-item" title="signIn">Inscription</a></p>
         <?php endif; ?>
      </div>
          <div class="widget latest-posts">
            <header>
              <h3 class="h6">Articles récents </h3>
            </header>
            <div class="blog-posts">
              <?php if ($latestPosts!= false){
              foreach($latestPosts as $latestPostIndex => $latestPost){ ?>
                <div class="item d-flex align-items-center">
                  <div class="image"><a href="post.php?idPost=<?=$latestPost['id']?>"><img src="img/<?=$latestPost['imageArticle']?>" alt="..." class="img-fluid"></a></div>
                  <div class="title"><strong><?=$latestPost['titre']?></strong>
                    <div class="d-flex align-items-center">
                      <div class="views"><?=$latestPost['dateArticle']?></div>
                      <div class="comments meta-last"><a href="post.php?idPost=<?=$latestPost['id']?>"><i class="fas fa-play text-secondary"></i></a></div>
                    </div>
                  </div>
                </div>
              <?php }}?>
          </div>
      </div>
          <!-- Widget [Categories Widget]-->
          <div class="widget categories">
            <header>
              <h3 class="h6">Categories</h3>
            </header>
            <?php if ($categories!= false):
              foreach($categories as $indexCategory => $category): if($category['nbart']>0):?>
            <div class="item d-flex justify-content-between"><a class="test" href="postsByCategory.php?idCategory=<?= $category['id'] ?>" data-id="<?= $category['id'] ?>" ><?= $category['name'] ?></a><span><?php 
            echo($category['nbart']); ?></span>
             </div>
           <?php endif; endforeach; endif; ?>
         </div>
      </aside>  
    </div>
</div>


    <!-- Page Footer-->
    <footer class="main-footer " >
        <div class="row">
          <div class="col-lg-1  to-top p-5">
                <i class="fas fa-arrow-circle-up text-primary"></i>
          </div>

          <div class="col-lg-5 P-3 ">
            <div class="logo p-2">
              <h6 class="text-white">Hiya Blog</h6>
              <p>By KLACH Intissar 3WAcademy</p>
            </div>
            <div class="contact-details p-3">
              <p>Phone: (00216) 52 648 637</p>
              <p>Email: <a href="mailto:intissar.klach.hajjaj@gmail.com">intissar.klach.hajjaj@gmail.com</a></p>
              <ul class="social-menu m-2">
                <li class="list-inline-item"><a href="#"><i class="fa fa-facebook text-primary"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-twitter text-primary"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-instagram text-primary"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-behance text-primary"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-pinterest text-primary"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-6 p-4">
            <div class="latest-posts">
              <?php if ($latestPosts!= false):
                foreach($latestPosts as $indexLatestPost => $latestPost):?>
                <a href="post.php?idPost=<?=$latestPost['id']?>" class="row" >
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="img/<?=$latestPost['imageArticle']?>"  alt="..." class="img-fluid"></div>
                  <div class="title"><strong><?=$latestPost['titre']?></strong><span class="date last-meta"><?=$latestPost['dateArticle']?></span></div>
                </div>
              </a>
              <?php  endforeach; endif; ?>
            </div>
          </div>
        </div>
    </footer>
    <!-- Javascript files-->
    <script
          src="https://code.jquery.com/jquery-3.3.1.min.js"
          integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
          crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"> </script>
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="vendor/jquery.cookie/jquery.cookie.js"> </script>
    <script src="vendor/@fancyapps/fancybox/jquery.fancybox.min.js"></script>
    <script src="js/front.js"></script>
     <script src="js/addFormControl.js"></script>
    

</body>
</html>
