
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Blog Femme Arabe</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="vendor/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="vendor/font-awesome/css/font-awesome.min.css">
    <!-- Custom icon font-->
    <link rel="stylesheet" href="css/fontastic.css">
    <!-- Google fonts - Open Sans-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Fancybox-->
    <link rel="stylesheet" href="vendor/@fancyapps/fancybox/jquery.fancybox.min.css">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="css/style.pink.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="css/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="favicon.png">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
    <header class="header"id="header">
      <!-- Main Navbar-->
      <nav class="navbar navbar-expand-lg"> 
        <div class="container">
          <!-- Navbar Brand -->
          <div class="navbar-header d-flex align-items-center justify-content-between ">
            <a href="blog.php" class="navbar-brand"><img src="img/log.jpg" width="100px"></a>
            <!-- Navbar Brand -->
            <!-- Toggle Button-->
            <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
          </div>
          <!-- Navbar Menu -->
          <div id="navbarcollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto"> 
              <li class="nav-item"><a href="blog.php" class="nav-link active ">Home</a>
              </li>
             <?php  foreach($categories as $indexCategories => $category){ if($category['nbart']>0){ ?>
              <li class="nav-item " ><a class="test nav-link" href="postsByCategory.php?idCategory=<?= $category['id'] ?>" data-id="<?= $v['id'] ?>" ><?=$category['name']?></a>
              </li>
              <?php }}?>
              <li class="nav-item"><a href="signUp.php" class="nav-link  ">Inscription</a>
              </li>
              <li class="nav-item"><a href="login.php" class="nav-link  ">Login</a>
              </li>
                <li class="nav-item"><a href="admin/showPosts.php" class="nav-link  ">Adminstration</a>
              </li>
              
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
      <div class="row">
           <main class="posts-listing col-lg-8 overflow-auto"> 
            <!-- Chargement du template PHTML spécifié par le programme PHP -->
            <?php include $template.'.phtml' ?>
          </main>
  
    <aside class="col-lg-4 fixed">
      <div class="widget search">
            <header>
              <h3 class="h6">Bienvenue :</h3>
            </header>
            <a href="" class=" btn btn-danger" >Déconnexion</a>
      </div>
          <!-- Widget [Search Bar Widget]-->
          <div class="widget search">
            <header>
              <h3 class="h6">Rechercher :</h3>
            </header>
            <form action="#" class="search-form">
              <div class="form-group">
                <input  id="search" type="search" placeholder="Que cherchez vous?">
                <button id="submitSearch" type="submit" class="submit"><i class="icon-search"></i></button>
              </div>
            </form>
          </div>
          <!-- Widget [Latest Posts Widget]        -->
          <div class="widget latest-posts">
            <header>
              <h3 class="h6">Articles récents </h3>
            </header>
            <div class="blog-posts">
              <?php if ($latestPosts!= false){
              foreach($latestPosts as $latestPostIndex => $latestPost){ ?>
                <div class="item d-flex align-items-center">
                  <div class="image"><a href="post.php?idPost=<?=$latestPost['id']?>"><img src="img/<?=$latestPost['imageArticle']?>" alt="..." class="img-fluid"></a></div>
                  <div class="title"><strong><?=$latestPost['titre']?></strong>
                    <div class="d-flex align-items-center">
                      <div class="views"><?=$latestPost['dateArticle']?></div>
                    </div>
                  </div>
                </div>
              <?php }}?>
          </div>
      </div>
          <!-- Widget [Categories Widget]-->
          <div class="widget categories">
            <header>
              <h3 class="h6">Categories</h3>
            </header>
            <?php if ($categories!= false){
              foreach($categories as $indexCategory => $category){  if($category['nbart']>0) {?>
            <div class="item d-flex justify-content-between"><a class="test" href="postsByCategory.php?idCategory=<?= $category['id'] ?>" data-id="<?= $category['id'] ?>" ><?= $category['name'] ?></a><span><?php 
            echo($category['nbart']); ?></span>
             </div>
           <?php }}} ?>
         </div>
      </aside>  
    </div>
    <div class="widget to-top">
      <i class="fas fa-angle-double-up"> Haut de page</i>
    </div>
 
</div>


    <!-- Page Footer-->
    <footer class="main-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <div class="logo">
              <h6 class="text-white">Hiya Blog</h6>
            </div>
            <div class="contact-details">
              <p>Phone: (00216) 52 648 637</p>
              <p>Email: <a href="mailto:intissar.klach.hajjaj@gmail.com">intissar.klach.hajjaj@gmail.com</a></p>
              <ul class="social-menu">
                <li class="list-inline-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-instagram"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-behance"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-pinterest"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
            <div class="menus d-flex">
              <ul class="list-unstyled">
                <li> <a href="#">My Account</a></li>
                <li> <a href="#">Add Listing</a></li>
              </ul>
              <ul class="list-unstyled">
                <li> <a href="#">Our Partners</a></li>
                <li> <a href="#">Inscription</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
            <div class="latest-posts">
              <?php if ($latestPosts!= false){
                   foreach($latestPosts as $indexLatestPost => $latestPost){ ?>
                <a href="post.php?idPost=<?=$latestPost['id']?>">
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="img/<?=$latestPost['imageArticle']?>"  alt="..." class="img-fluid"></div>
                  <div class="title"><strong><?=$latestPost['titre']?></strong><span class="date last-meta"><?=$latestPost['dateArticle']?></span></div>
                </div>
              </a>
              <?php  }}?>
              
               </div>
          </div>
        </div>
      </div>


     
    </footer>
    <!-- Javascript files-->
    <script
          src="https://code.jquery.com/jquery-3.3.1.min.js"
          integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
          crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"> </script>
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="vendor/jquery.cookie/jquery.cookie.js"> </script>
    <script src="vendor/@fancyapps/fancybox/jquery.fancybox.min.js"></script>
    <script src="js/front.js"></script>

</body>
</html>
