<main class=" col-lg-8 "> 
                <div class="container" id="register">
                  <header>
                    <h3 class="h6">Inscription</h3>
                  </header>
                  <form action="addUser.php" class="register-form" enctype="multipart/form-data" method="post">
                    <div class="row">
                      <div class="form-group col-md-6">
                        <input type="text" name="userFirstName" id="firstName" placeholder="Votre Prénom" class="form-control">
                        <div class = "text-danger" id="invalidprenom"></div>
                        <div class="valid-feedback" id="validprenom"></div>
                      </div>
                      <div class="form-group col-md-6">
                        <input type="text" name="userLastName" id="lastName" placeholder="Votre nom" class="form-control">
                        <div class = "text-danger" id="invalidnom"></div>
                        <div class="valid-feedback" id="validnom"></div>
                      </div>
                      <div class="form-group col-md-6">
                        <input type="email" name="userEmail" id="email" placeholder="Votre addresse email" class="form-control">
                        <div class = "text-danger" id="invalidmail"></div>
                        <div class="valid-feedback" id="validmail"></div>
                      </div>
                      <div class="form-group col-md-6">
                        <input type="password" name="userPassword" id="password" placeholder="Votre mot de passe" class="form-control">
                        <div class = "text-danger" id="invalidpass"></div>
                        <div class="valid-feedback" id="validpass"></div>
                      </div>
                      <div class="form-group col-md-6">
                       <input type="file" name="userPhoto" id="userPhoto">
                      </div>
                      
                      <div class="form-group col-md-12">
                        <button type="submit" class="btn btn-secondary" id="registerUser">S'inscrire</button>
                      </div>
                    </div>
                  </form>
                </div>
              </main>


