
	<div class="container">
		<header>
			<h1 class="headingPage">Ajouter une catégorie :</h1>
	    </header>
		 
		<div class="boxAddPost boxAddCategory">
			<form method="POST" action="addCategory.php">
				<label for="oldCategory">Liste des catégories déjà existants :</label>
				<select id="oldCategory" name="oldCategory">
					<?php if ($categories!= false){
		        foreach($categories as $index => $category){ ?>
					<option value="<?= $category['id']?>"><?= $category['name'] ?></option>
					<?php }} ?>
				</select>
				<button type="submit"><i class="fas fa-minus-circle"></i></button>
				
				<hr>
				<label for="category">Catégorie à ajouter :<span style="color: red"><?php if(($trouve== true) and (isset($_POST['submit'])))  { echo('Catégorie existante déjà!');}      ?> </span></label>
				<input class="form-control" id="category" type="text" name="title">
				<input type="submit" name="submit" id="btnSubmit" value="Ajouter">
			</form>
		</div>
	</div>
