
	<div class="container">
		<div class = "page-header">
			<h2 class="text-center text-secondary">Ajouter un article</h2>
		</div>
			<form action="" method="POST" enctype="multipart/form-data">
				<div class="form-group row">
					<div class="col-sm-12 col-md-6 col-lg-6">
						<label class="label-form" for="title">Titre de l'article :</label>
						<input class="form-control" id="title" type="text" name="title">
					</div>
					<div class="col-sm-12 col-md-6 col-lg-6">
						<label class="label-form" for="title">Catégoie:</label>
						<select class="form-control" id="Category" name="Category">
							<?php if ($categories!= false):
							foreach($categories as $indexCat => $category): ?>
							<option value="<?= $category['name']?>"><?= $category['name'] ?>
							</option>
							<?php endforeach; endif;?>
						</select>
					</div>
				</div>
				<div class="row">
					<label class="label-form" for="description">Corps de l'article :</label>
					<textarea class="form-control" id="description" name="description" rows="10"  placeholder="Ecrire votre article ici ..."></textarea>
				</div>
				<div class="form-group mt-3">
      					<label class="label-form" >Télecharger une image :</label>
      					<input class="form-control-file" type="file" name="fileToUpload" id="fileToUpload">
      			</div>			
				<div class=" row">
					<p class="h5  col-sm-12 col-md-8 ">Publier l'Article en tant que :<strong class="text-info"><?php echo($_SESSION['last_Name']." ".$_SESSION['first_Name'] ); ?></strong></p>
					<input class="btn btn-success col-sm-12 col-md-4" type="submit" name="submit" id="btnSubmit" value="Enregistrer">
				</div>
				
				</div>
				
				
			</form>
	
	</div>
