
	<div class="container-fluid">
		<div class = "page-header p-5">
				<h2 class="text-center text-secondary">Géstion des utilisateurs</h2>
		</div>
		<table class="table table-hover" id="myTable">
			<thead>
	   				<tr>
	      				<th  class="d-none d-lg-block" scope="col">Image</th>
	      				<th scope="col">Prévilege</th>
	      				<th scope="col">Nom & prénom</th>
	      				<th scope="col">mail</th>
	      				<th scope="col">Supprimer</th>
	    			</tr>
  			</thead>
  			<tbody>
  				<?php if ($users!= false):
					foreach($users as $index => $user):?>
				<tr>
						<td class="d-none d-lg-block"><img src="../img/<?=$user['imgUser']?>"  class=" rounded-circle w-1" width="50px" height="50px" alt="img user"  ></td>
						<td><?= $user['privilégie']?></td>
						<td><?=$user['last_Name']?> <?=$user['first_Name']?></td>
						<td><?= $user['email']?></td>
						<td>
							<?php if ($user['privilégie']=='user'): ?>
							<a href="deleteUser.php?id=<?=$user['id']?>" title="supprimer l'utilisateur"><i class="fas fa-trash-alt text-danger"></i></a>
						<?php endif; ?>
						</td>
				</tr>
				<?php endforeach; endif; ?>	
  			</tbody>
  		</table>
	</div>
	<script type="text/javascript">
	$(document).ready( function () {
    $('#myTable').DataTable();

} );
</script>


