	
	<div class="container-fluid">
    <?php if ($singlePost!= false): ?>
		<div class="container ">
			<div class = "page-header p-5">
				<h2 class="text-secondary"> <?= $singlePost['titre'] ?></h2>
				<p>
					<small>
					<?php echo $_SESSION['first_Name'].' '.$_SESSION['last_Name'] ?>	
					</small> | 
					<small>
					<?= $singlePost['dateArticle'] ?>
					</small> | 
					<small>
					<?=$singlePost['name']?>
					</small>
				</p>
			</div>
			<div class="row">
				<p class="col-md-6 col-xs-12"><?= $singlePost['body'] ?></p>
				<img src="../img/<?=$singlePost['imageArticle']?>" class="col-md-6 col-xs-12" >
			</div>
		</div>
		<?php endif;
		if($comments):?>
		<div>
		<h4 class="text-dark">Les commentaires récents:</h4>
		</div>
           <?php  endif; ?>
		<div id="comments">
		   <?php foreach($comments as $indexComment => $comment): ?>
			<div class="card bg-light mb-3" >
  				<div class="card-header ">
  					<div class="row">
  						<p class="col-md-10"><?=$comment['first_Name'] ?>  <?=$comment['last_Name'] ?></p>
  						<?php  ?>
  						<a class="col-md-2" href="deleteComment.php?idc=<?=$comment['id'] ?>&ida=<?=$comment['idArticle'] ?>"><i class="fas fa-trash-alt"></i></a>
  					</div>
  				</div>
  				<div class="card-body">
   					 <h4 class="card-title"><small><?=$comment['dateComment']?></small></h4>
   					 <p class="card-text"><?=$comment['body'] ?></p>
  				</div>
			</div>
			<?php endforeach; ?>	
		</div>
	</div>
	

