	
	<h1 class="text-center headingPage">Gérer Votre Article</h1>
	<div class="container-fluid">
    <?php if ($singlePost!= false)
    { ?>
		<div class="container ">
			<img src="../img/<?=$singlePost['imageArticle']?>" class='imgPost' >
			<h2> <?= $singlePost['titre'] ?></h2>
			<p><small><?php echo $singlePost['first_Name'].' '.$singlePost['last_Name'] ?></small> | <small><?= $singlePost['dateArticle'] ?></small> | <small><?=$singlePost['name']?></small>
			</p>
			<p><?= $singlePost['body'] ?></p>
			<div style="text-align: center;">
			<a href="updatePost.php?id=<?=$singlePost['id']?>"><input type="button" name="Modifier" value=" Modifier "></a>
			<a href="deletePost.php?id=<?=$singlePost['id']?>"><input type="button" name="delete" value=" Supprimer "></a>
		</div>
		</div>
		<?php }
		if($comments)
			{?>
		<div>
		<hr style=" border: 1px solid hotpink">
		<h3>Les commentaires récents:</h3>
		</div>
           <?php  }?>
		<div id="comments">
			<?php if ($comments!= false){
		   foreach($comments as $indexComment => $comment){ ?>
			<div class=" container post" style="background-color:  #d6dbdf ;">
				<h5><?=$comment['nameCommentor'] ?></h5>
				<small><?=$comment['dateComment']?></small>
				<p><?=$comment['body'] ?></p>
				<a href="deleteComment.php?idc=<?=$comment['id'] ?>&ida=<?=$comment['idArticle'] ?>"><i class="fas fa-trash-alt"></i></a>
			</div>
			<?php
			 }
		}?>	
		</div>
	</div>
	

